---
  - name: Install the httpd apps
    yum: name=httpd use_backend=yum state=present
  - name: start the httpd service
    service: name=httpd state=started
  - name: example copying file with owner and permissions
    copy:
      src: /opt/test.sh
      dest: /tmp/test.sh
      mode: 0644
  - script: /tmp/test.sh 
